load "synth1-communications-heatmap.plt"
load "synth1-path-cost-comparison.plt"
load "synth1-path-cost-comparison-optimal.plt"
load "synth1-path-cost-comparison-relative.plt"
load "synth1-piz-routes.plt"
load "synth1-routing-tables.plt"
load "synth1-routing-tables-bits.plt"
load "synth1-routing-tables-heatmap.plt"